{
 "title": "Zabbix Alertmanager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "labelselector", "label": "labelselector", "query": "${VAR_LABELSELECTOR}" },
   { "name": "labelvalue", "label": "labelvalue", "query": "${VAR_LABELVALUE}" }
  ]
 },
 "panels": [
  {
   "title": "Alerts sent to Zabbix",
   "type": "graph",
   "description": "Alerts sent to Zabbix",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(alerts_sent_total{$labelselector=\"$labelvalue\"}[$__interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Failed Alerts",
   "type": "graph",
   "description": "Alerts sent to Zabbix",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(alerts_errors_total{$labelselector=\"$labelvalue\"}[$__interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{$labelselector=\"$labelvalue\"}",
     "legendFormat": "{{kubernetes_pod_name}} resident  memory "
    },
    {
     "expr": "process_virtual_memory_bytes{$labelselector=\"$labelvalue\"}",
     "legendFormat": "{{kubernetes_pod_name}} virtual memory "
    }
   ]
  },
  {
   "title": "Gargage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{$labelselector=\"$labelvalue\",quantile=\"0.75\"}",
     "legendFormat": "{{quantile}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "go_gc_duration_seconds{$labelselector=\"$labelvalue\",quantile=\"1\"}",
     "legendFormat": "{{quantile}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{$labelselector=\"$labelvalue\"}[$__interval])",
     "legendFormat": "{{kubernetes_pod_name}} open"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{$labelselector=\"$labelvalue\"}",
     "legendFormat": "{{kubernetes_pod_name}} open"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(zal_build_info{$labelselector=\"$labelvalue\"}) by (goversion, kubernetes_pod_name, version)"
    }
   ]
  },
  {
   "title": "Modules",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(go_mod_info{$labelselector=\"$labelvalue\"})  by (exported_name, version)"
    }
   ]
  }
 ]
}